name: Deploy

on:
  push:
    branches: [main]
  # специальное событие, которое происходит при ручном вызове workflow
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Copy files to the server
        # через переменные окружения передаем SSH ключ
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        # заливаем файлы при помощи rsync
        run: |
          rsync -a --progress --human-readable --delete \
          --exclude-from '.gitignore' \
          --exclude .gitignore \
          --exclude .git \
          . deploy@157.245.88.102:~/realworld/
      # job для перезапуска приложения при помощи pm2
      - name: Restart the application
        run: |
          ssh deploy@157.245.88.102 "pushd ~/realworld && npm install && popd && pm2 restart realworld"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
